[FE] [MODIFY] EIP 103 adjust hardcoded api requests
Guardos-Epitech/Guardos-Resto pull request #18
Opened 2023-03-27 20:50 UTC by wernerramon

Added restaurant selector for "DishForm" and "ProductForm".  Now the restaurant is not hardoded anymore and you can select the fitting restaurant for the dish or product from all available restaurants.

2023-04-04 15:04 UTC, JosefineM2000 requested changes

2023-04-17 19:10 UTC, wernerramon commented on backend/src/controllers/dishesController.ts
> +import { ICategoryFE } from '../models/categoryInterfaces';
changed order

2023-04-17 19:10 UTC, wernerramon commented on backend/src/controllers/dishesController.ts
>  export async function getDishesByRestaurantID(restaurantId: number) {
unused function removed

2023-04-17 19:10 UTC, wernerramon commented on backend/src/controllers/dishesController.ts
> +  return Restaurant.find({ _id: restaurantId }, 'dishes');
not important anymore because function is gone

2023-04-17 19:11 UTC, wernerramon commented on web/src/components/forms/DishForm/DishForm.tsx
> +import { getAllRestoProducts, getAllProducts } from "@src/services/productCalls";
removed getAllRestoProducts

2023-04-17 19:11 UTC, wernerramon commented on web/src/components/forms/DishForm/DishForm.tsx
> +import { IProduct, IRestaurantFrontEnd, IRestoName } from "@src/model/restaurantInterfaces";
removed IRestoName

2023-04-17 19:12 UTC, wernerramon commented on web/src/components/forms/DishForm/DishForm.tsx
> +  const suggestionsAller: string[] = ["No Allergens", "Celery", "Gluten", "Crustaceans", "Eggs", "Fish", "Lupin", "Milk", "Molluscs", "Mustard", "Nuts", "Peanuts", "Sesame seeds", "Soya", "Sulphur di
added line split

2023-04-17 19:12 UTC, wernerramon commented on web/src/components/forms/DishForm/DishForm.tsx
> +  selCat?: string[],
renamed to clearer names

2023-04-17 19:13 UTC, wernerramon commented on web/src/components/forms/DishForm/DishForm.tsx
> +  }, []);;
removed double semicolon

2023-04-17 19:13 UTC, wernerramon commented on web/src/components/forms/DishForm/DishForm.tsx
> +    getAllProducts().then((res) => {
done

2023-04-17 19:13 UTC, wernerramon commented on web/src/components/forms/DishForm/DishForm.tsx
> +    getAllResto().then((res) => {
done

2023-04-17 19:14 UTC, wernerramon commented on web/src/components/forms/ProductForm/ProductForm.tsx
> +import { IIngredient, IProduct, IRestaurantFrontEnd, IRestoName } from "@src/model/restaurantInterfaces";
added line split

2023-04-17 19:14 UTC, wernerramon commented on web/src/components/forms/ProductForm/ProductForm.tsx
> +import { getAllResto } from "@src/services/restoCalls";
moved getAllResto above IIngredient

2023-04-17 19:14 UTC, wernerramon commented on web/src/components/forms/ProductForm/ProductForm.tsx
> +  let restoName = "" as string;
removed unused

2023-04-17 19:14 UTC, wernerramon commented on web/src/components/forms/ProductForm/ProductForm.tsx
> +  const [selectedResto, setSelectedResto] = useState([] as IRestoName[]);
removed unused

2023-04-17 19:15 UTC, wernerramon commented on web/src/components/forms/ProductForm/ProductForm.tsx
> +  let restotmp: string[] = [];
renamed to selectedResto

2023-04-17 19:15 UTC, wernerramon commented on web/src/components/forms/ProductForm/ProductForm.tsx
> +    getAllResto().then((res) => {
done

2023-04-17 19:15 UTC, wernerramon commented on web/src/components/forms/ProductForm/ProductForm.tsx
> +      restoNameList = restoList.map((restaurant) => ({ name: restaurant.name }));
added line split

2023-04-17 19:15 UTC, wernerramon commented on web/src/components/forms/ProductForm/ProductForm.tsx
> +              getOptionLabel={(option) => (option ? (option as IRestoName).name : "")}
added line split

2023-04-17 19:15 UTC, wernerramon commented on web/src/components/forms/ProductForm/ProductForm.tsx
> +                restotmp = value.map((restoNameVar: IRestoName) => restoNameVar.name);
added line split

2023-04-17 19:15 UTC, wernerramon commented on web/src/components/menu/Dish/Dish.tsx
>  import AllergenTags from "@src/components/menu/AllergenTags/AllergenTags";
removed unused

2023-04-17 19:16 UTC, wernerramon commented on web/src/components/menu/Dish/Dish.tsx
> +  const { name, allergens, description, price, pictures, resto } = dish;
removed unused

2023-04-17 19:16 UTC, wernerramon commented on web/src/model/dishInterfaces.ts
>  }
added empty line

2023-04-17 19:16 UTC, wernerramon commented on web/src/model/restaurantInterfaces.ts
>  }
added empty line

2023-04-17 19:16 UTC, wernerramon commented on web/src/pages/EditDishPage/EditDishPage.tsx
> +  const { name, products, description, price, allergens, resto, category } = dish;
added line split

2023-04-17 19:16 UTC, wernerramon commented on web/src/pages/EditDishPage/EditDishPage.tsx
> +  const selAllergens: string[] = allergens.toString().split(",");
done

2023-04-17 19:16 UTC, wernerramon commented on web/src/pages/EditDishPage/EditDishPage.tsx
> +  const selCat: string[] = [category.menuGroup];
renamed all sel* variables

2023-04-17 19:17 UTC, wernerramon commented on web/src/services/dishCalls.ts
> +}
added semicolon at the end

2023-04-17 19:17 UTC, wernerramon commented on web/src/services/productCalls.ts
> +}
added semicolon at the end

2023-04-17 19:17 UTC, wernerramon commented on web/src/services/dishCalls.ts
> +}
added empty line

2023-04-17 19:17 UTC, wernerramon commented on web/src/services/productCalls.ts
> +}
added empty line

2023-04-17 19:17 UTC, wernerramon commented on web/src/services/restoCalls.ts
> +}
added empty line

2023-04-17 19:17 UTC, wernerramon commented on web/src/services/restoCalls.ts
> +}
added semicolon at the end

2023-04-20 12:41 UTC, merged